<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>payment_tax_invoice_calculator_icon_188774.ico</ApplicationIcon>
    <PackageIcon>payment_tax_invoice_calculator_icon_188774.ico</PackageIcon>
    <AssemblyVersion>0.2.0.3</AssemblyVersion>
    <FileVersion>0.2.0.3</FileVersion>
    <RepositoryUrl>https://github.com/emjotbee/PrawaAutorskie</RepositoryUrl>
    <RepositoryType>GitHub</RepositoryType>
    <PackageProjectUrl>https://github.com/emjotbee/PrawaAutorskie</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\..\..\Desktop\PrawaAutorskie\payment_tax_invoice_calculator_icon_188774.ico">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ClosedXML">
      <HintPath>..\published\ClosedXML.dll</HintPath>
    </Reference>
    <Reference Include="DocumentFormat.OpenXml">
      <HintPath>..\published\DocumentFormat.OpenXml.dll</HintPath>
    </Reference>
    <Reference Include="ExcelNumberFormat">
      <HintPath>..\published\ExcelNumberFormat.dll</HintPath>
    </Reference>
    <Reference Include="Google.Apis">
      <HintPath>..\published\Google.Apis.dll</HintPath>
    </Reference>
    <Reference Include="Google.Apis.Auth">
      <HintPath>..\published\Google.Apis.Auth.dll</HintPath>
    </Reference>
    <Reference Include="Google.Apis.Auth.PlatformServices">
      <HintPath>..\published\Google.Apis.Auth.PlatformServices.dll</HintPath>
    </Reference>
    <Reference Include="Google.Apis.Core">
      <HintPath>..\published\Google.Apis.Core.dll</HintPath>
    </Reference>
    <Reference Include="Google.Apis.Drive.v3">
      <HintPath>..\published\Google.Apis.Drive.v3.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\published\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="ScottPlot">
      <HintPath>..\published\ScottPlot.dll</HintPath>
    </Reference>
    <Reference Include="ScottPlot.WinForms">
      <HintPath>..\published\ScottPlot.WinForms.dll</HintPath>
    </Reference>
    <Reference Include="System.Data.SqlClient">
      <HintPath>..\published\System.Data.SqlClient.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>